name: Ejemplo de Ejecuci칩n de index.js

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de tu rama principal si es diferente
  schedule:
    - cron: '0 * * * *'  # Esto ejecutar치 la acci칩n cada hora

jobs:
  ejecutar_index_js:
    runs-on: ubuntu-latest  # Puedes cambiar a otro sistema operativo si es necesario

    steps:
    - name: Checkout del c칩digo
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar index.js
      run: node index.js
